add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_0]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_1]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_2]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_3]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_4]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_5]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_6]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_7]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_8]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_9]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_10]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_11]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_12]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_13]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_14]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_15]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_16]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_17]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_18]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_19]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_20]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_21]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_22]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_23]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_24]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_25]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_26]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_27]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_28]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_29]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_30]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr0_31]] -clear_locs

add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_0]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_1]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_2]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_3]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_4]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_5]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_6]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_7]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_8]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_9]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_10]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_11]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_12]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_13]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_14]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_15]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_16]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_17]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_18]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_19]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_20]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_21]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_22]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_23]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_24]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_25]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_26]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_27]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_28]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_29]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_30]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_01_slr1_31]] -clear_locs

add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_0]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_1]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_2]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_3]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_4]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_5]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_6]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_7]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_8]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_9]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_10]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_11]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_12]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_13]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_14]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_15]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_16]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_17]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_18]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_19]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_20]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_21]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_22]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_23]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_24]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_25]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_26]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_27]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_28]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_29]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_30]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR0 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr0_31]] -clear_locs

add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_0]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_1]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_2]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_3]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_4]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_5]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_6]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_7]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_8]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_9]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_10]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_11]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_12]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_13]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_14]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_15]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_16]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_17]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_18]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_19]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_20]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_21]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_22]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_23]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_24]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_25]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_26]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_27]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_28]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_29]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_30]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR1 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr1_31]] -clear_locs

add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_0]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_1]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_2]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_3]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_4]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_5]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_6]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_7]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_8]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_9]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_10]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_11]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_12]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_13]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_14]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_15]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_16]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_17]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_18]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_19]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_20]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_21]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_22]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_23]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_24]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_25]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_26]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_27]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_28]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_29]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_30]] -clear_locs
add_cells_to_pblock pblock_dynamic_SLR2 [get_cells [list pfm_top_i/dynamic_region/FinalBFS_32_1/inst/top_i/p1_end_q_02_slr2_31]] -clear_locs
